/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-05-31 08:58:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("      <div class=\"inner_footer\">\r\n");
      out.write("        <div class=\"cc_footer\">\r\n");
      out.write("          <!-- cc = company calls -->\r\n");
      out.write("          <h2 class=\"cc_tit\">더 궁금한것이 있으세요?\r\n");
      out.write("          </h2>\r\n");
      out.write("          <div class=\"cc_view cc_kakao\">\r\n");
      out.write("            <a href=\"#\" class=\"footerTag\">\r\n");
      out.write("              <div class=\"footerLink\">1:1 카톡상담</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"footerTag\">\r\n");
      out.write("              <div class=\"footerLink\">자주묻는질문</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"footerTag\">\r\n");
      out.write("              <div class=\"footerLink\">02-1561-4463</div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <strong class=\"copy\">Copyright &copy;2023 PetSisters. All Right Reserved.</strong>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"company_info\">\r\n");
      out.write("          <h2 class=\"cc_tit\">펫시스터즈\r\n");
      out.write("            <img id=\"footerLogo\" src=\"/resources/img/main/푸터로고.png\" alt=\"footerLogo\">\r\n");
      out.write("          </h2>\r\n");
      out.write("          <div class=\"spec_info\">\r\n");
      out.write("            주식회사 개봐주는언니들\r\n");
      out.write("            <span class=\"bar\">I</span>\r\n");
      out.write("            대표 : 김가현\r\n");
      out.write("            <br>\r\n");
      out.write("            사업자등록번호 : 215-15-41572\r\n");
      out.write("            <br>\r\n");
      out.write("            대표전화 : 02-1588-1548\r\n");
      out.write("            <span class=\"bar\">I</span>\r\n");
      out.write("            통신판매업 신고 : 2011-경기광명-1384 <br>\r\n");
      out.write("            팩스 : 02-1568-4548\r\n");
      out.write("            <br>\r\n");
      out.write("            사업장 소재지 : 서울특별시 영등포구 선유동2로 57 이레빌딩\r\n");
      out.write("            <br>\r\n");
      out.write("            개인정보 보호 책임자 : 조승호 <a href=\"#\">jjh156@naver.com</a>\r\n");
      out.write("            <br>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"link_footer\">\r\n");
      out.write("        <a href=\"\">이용약관</a>\r\n");
      out.write("        <a href=\"\">위치정보활용약관</a>\r\n");
      out.write("        <a href=\"\">개인정보취급방침</a>\r\n");
      out.write("        <a href=\"\">안정보상프로그램</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
