/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-06-12 05:46:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pet_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  \r\n");
      out.write("  <!-- header css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/css/member/pet_profile.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/css/common/memberForm.css\">\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/common.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <title>마이페이지_펫프로필관리</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- 헤더 영역 시작-->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("	 \r\n");
      out.write("  <!-- 헤더 영역 끝-->\r\n");
      out.write("\r\n");
      out.write("  <div id=\"Container-Wrapper\">\r\n");
      out.write("    <!-- 페이지 영역 시작 -->\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("      <div id=\"main\">\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("          <div class=\"page_aticle aticle_type2\">\r\n");
      out.write("            <!-- 사이드 메뉴바 -->\r\n");
      out.write("            <div id=\"snb\" class=\"snb_my\" style=\"position: absolute;\">\r\n");
      out.write("              <img src=\"/resources/img/main/사이드바이미지.png\" alt=\"sideBarImg\">\r\n");
      out.write("              <h2 class=\"tit_snb\">My Page</h2>\r\n");
      out.write("              <div class=\"inner_sub\">\r\n");
      out.write("                <ul class=\"list_menu\">\r\n");
      out.write("                  <li class=\"on\">\r\n");
      out.write("                    <a href=\"myProfile.me\">내 프로필</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"petProfile.me\">반려동물 프로필</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"petsiterLike.me\">펫시터 찜</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"myBoard.me\">내 게시글 및 댓글</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"reservationList\">예약 조회</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"journalList\">돌봄 일지</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 사이드 메뉴바 끝 -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 본문 영역-->\r\n");
      out.write("            <div id=\"viewOrderList\" class=\"page_section section_orderlist\">\r\n");
      out.write("              <div class=\"page_section section_destination\">\r\n");
      out.write("                <!-- 이 영역 안에서 페이지 작업 하시면 됩니다 -->\r\n");
      out.write("                <!--<div style=\"height: 1000px; background-color: beige;\"></div> -->\r\n");
      out.write("                <div id=\"titleWrapper\">\r\n");
      out.write("                  <h3 class=\"title_11\">펫 프로필 상세정보</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form id=\"profileWrapper\">\r\n");
      out.write("                  <hr>\r\n");
      out.write("                    <div class=\"file_main\">\r\n");
      out.write("                      <label>사진</label>\r\n");
      out.write("                      <div class=\"file_change\">\r\n");
      out.write("                        <img class=\"profile_img\" src=\"/resources/img/main/로이-4052.jpg\" />\r\n");
      out.write("                        <div class=\"profile_con\">\r\n");
      out.write("                          <button type=\"button\" class=\"img_btn\">사진변경</button>\r\n");
      out.write("                          <p>등록된 사진은 반려견의 프로필입니다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <label>이름</label>\r\n");
      out.write("                  <input class=\"pet_name\" placeholder=\"찰스\" />\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <label>성별</label>\r\n");
      out.write("                  <input type=\"checkbox\" id=\"Male\" value=\"M\" name=\"gender\"> 남\r\n");
      out.write("                  <input type=\"checkbox\" id=\"Female\" value=\"F\" name=\"gender\"> 여\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <label>견종</label>\r\n");
      out.write("                  <input class=\"pet_type\" placeholder=\"슈나우저\" />\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <label>생일</label>\r\n");
      out.write("                  <input class=\"pet_birth\" placeholder=\"220506\" />\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <label>몸무게</label>\r\n");
      out.write("                  <input class=\"pet_kg\" placeholder=\"5kg\" />\r\n");
      out.write("                  <hr>\r\n");
      out.write("                  <span class=\"fix checkbox\">\r\n");
      out.write("                    <label>중성화</label><br>\r\n");
      out.write("                    <input type=\"checkbox\" name=\"yes\" id=\"yes\" value=\"Y\"> Yes\r\n");
      out.write("                    <input type=\"checkbox\" name=\"no\" id=\"no\" value=\"N\"> No <br>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <button type=\"submit\" class=\"update_btn\">수정하기</button>\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("                <!-- 이 영역 안에서 페이지 작업 하시면 됩니다 -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 본문 영역 끝-->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Footer 영역 시작 -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write(" \r\n");
      out.write("  <!-- Footer 영역 끝 -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
