/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-06-02 07:34:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class supportInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1685437075587L));
    _jspx_dependants.put("jar:file:/C:/final%20project/PetSisters/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/member/supportInfo.css\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/common.jsp", out, false);
      out.write("\r\n");
      out.write("<title>펫시스터즈</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("    	\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 본문 시작 -->\r\n");
      out.write("\r\n");
      out.write("    <main class=\"supportInfoArea\">\r\n");
      out.write("      <section class=\"introductionSection\">\r\n");
      out.write("        <div class=\"videoArea\">\r\n");
      out.write("          <video loop=\"\" muted=\"\" autoplay=\"\" playsinline=\"\" webkit-playsinline=\"true\" \r\n");
      out.write("          style=\"display:flex;object-fit:cover;width:100%;height:770px;z-index:10\">\r\n");
      out.write("          <source type=\"video/mp4\" src=\"/resources/video/introductionVideo.mp4\"></video>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"adArea\">\r\n");
      out.write("          <div class=\"mainSentence\">\r\n");
      out.write("            가정집 펫시터 업계 1위, <br>\r\n");
      out.write("            펫시스터즈와 함께해요 <br>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"subSentence\">\r\n");
      out.write("            우리집에서 사랑스러운 강아지를 돌보며 수익을 벌어요 <br>\r\n");
      out.write("            혼자 남겨진 반려동물에게 행복한 시간을 선물해볼까요? <br>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a class=\"support\" href=\"supportForm.me\" onclick=\"return checkLogin();\">\r\n");
      out.write("            <p>지원하기</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <section class=\"processSection\">\r\n");
      out.write("        <div class=\"processContentArea\">\r\n");
      out.write("          <p style=\"color: rgb(77, 80, 85); font-size: 35px; font-weight: 600;\r\n");
      out.write("          letter-spacing: -0.3px; line-height: 37px; padding: 0; margin: 0;\">\r\n");
      out.write("          펫시스터즈 펫시터는 이렇게 활동해요!</p>\r\n");
      out.write("          <div><img alt=\"\" src=\"/resources/img/member/1-2-3.png\" style=\"width: 762px;  margin-top: 50px;\"></div>\r\n");
      out.write("          <div style=\"display: flex; flex-direction: row;\">\r\n");
      out.write("            <div style=\"width: 364px;\">\r\n");
      out.write("              <p style=\"margin-top: 50px;  font-size: 25px; \r\n");
      out.write("              letter-spacing: 0.2px; line-height: 31px; \">예약 수락</p>\r\n");
      out.write("              <p style=\"margin-top: 24px;  font-size: 17px; \r\n");
      out.write("              line-height: 30px; letter-spacing: 0.2px;\">\r\n");
      out.write("              내 예약관리에서 간편하게<br>\r\n");
      out.write("              가능한 날짜의 예약을 수락해보세요.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"width: 364px;\">\r\n");
      out.write("              <p style=\"margin-top: 50px;  font-size: 25px; \r\n");
      out.write("              letter-spacing: 0.2px; line-height: 31px; \">돌봄 및 일지쓰기</p>\r\n");
      out.write("              <p style=\"margin-top: 24px;  font-size: 17px; \r\n");
      out.write("              line-height: 30px; letter-spacing: 0.2px;\">\r\n");
      out.write("              우리 집에서 반려동물을 돌보며,<br>\r\n");
      out.write("              시간별로 돌봄 일지를 작성합니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <p style=\"margin-top: 50px; \r\n");
      out.write("              font-size: 25px; letter-spacing: 0.2px; line-height: 31px; \r\n");
      out.write("              \">정산 받기</p>\r\n");
      out.write("              <p style=\"margin-top: 24px;  font-size: 17px; \r\n");
      out.write("              line-height: 30px; letter-spacing: 0.2px;\">\r\n");
      out.write("              수익을 실시간으로 확인하고<br>\r\n");
      out.write("              주 단위로 정산을 받아보세요!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <section style=\"width: 100%; height: 1030px; display: flex; flex-direction: column; \r\n");
      out.write("      justify-content: center; align-items: center;\">\r\n");
      out.write("        <div style=\"width: 1020px; margin: 0px auto; display: flex; flex-direction: row; \r\n");
      out.write("        justify-content: space-between;\">\r\n");
      out.write("          <div style=\"width: 273px; align-items: center; border-bottom: 1px solid rgb(231, 231, 240); \r\n");
      out.write("          padding-bottom: 70px;\">\r\n");
      out.write("            <img alt=\"\" src=\"/resources/img/member/편안한근무환경.png\" style=\"height: 120px; \r\n");
      out.write("            display: block; margin-left: -15px;\">\r\n");
      out.write("            <p style=\"margin-top: 21px; color: rgb(77, 80, 85); font-size: 25px; line-height: 30px; \r\n");
      out.write("            letter-spacing: -0.3px; font-weight: 500;\">편안한 근무 환경</p>\r\n");
      out.write("            <p style=\"color: rgb(77, 80, 85); font-size: 17px; line-height: 30px; margin-top: 45px; \r\n");
      out.write("            width: max-content;\">편안한 우리 집에서 사랑스러운<br>강아지들과 행복한 시간을 보낼 수 있어요.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"width: 273px; align-items: center; border-bottom: 1px solid rgb(231, 231, 240); \r\n");
      out.write("          padding-bottom: 70px;\">\r\n");
      out.write("            <img alt=\"\" src=\"/resources/img/member/자유로운업무시간.png\" style=\"height: 120px; \r\n");
      out.write("            display: block; margin-left: -15px;\">\r\n");
      out.write("            <p style=\"margin-top: 21px; color: rgb(77, 80, 85); font-size: 25px; line-height: 30px; \r\n");
      out.write("            letter-spacing: -0.3px; font-weight: 500;\">자유로운 업무 시간</p>\r\n");
      out.write("            <p style=\"color: rgb(77, 80, 85); font-size: 17px; line-height: 30px; margin-top: 45px; \r\n");
      out.write("            width: max-content;\">자유로운 휴무일 관리로 여가생활을<br>즐기며 원하는 날에만 일할 수 있어요.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"width: 273px; align-items: center; border-bottom: 1px solid rgb(231, 231, 240); \r\n");
      out.write("          padding-bottom: 70px;\">\r\n");
      out.write("            <img alt=\"\" src=\"/resources/img/member/월평균100만원수익.png\" style=\"height: 120px; \r\n");
      out.write("            display: block; margin-left: -15px;\">\r\n");
      out.write("            <p style=\"margin-top: 21px; color: rgb(77, 80, 85); font-size: 25px; line-height: 30px; \r\n");
      out.write("            letter-spacing: -0.3px; font-weight: 500;\">월 평균 100만원 수익</p>\r\n");
      out.write("            <p style=\"color: rgb(77, 80, 85); font-size: 17px; line-height: 30px; margin-top: 45px; \r\n");
      out.write("            width: max-content;\">하루 평균 50,000원으로 한 달 20일<br>돌봄 진행 시 100만원의 수익이 발생해요.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"width: 1020px; margin: 70px auto 0px; display: flex; flex-direction: row; \r\n");
      out.write("        justify-content: space-between;\">\r\n");
      out.write("          <div style=\"width: 273px; align-items: center;\">\r\n");
      out.write("            <img alt=\"\" src=\"/resources/img/member/펫시터헬프시스템.png\" style=\"height: 120px; \r\n");
      out.write("            display: block; margin-left: -15px;\">\r\n");
      out.write("            <p style=\"margin-top: 21px; color: rgb(77, 80, 85); font-size: 25px; line-height: 30px; \r\n");
      out.write("            letter-spacing: -0.3px; font-weight: 500;\">펫시터 헬프 시스템</p>\r\n");
      out.write("            <p style=\"color: rgb(77, 80, 85); font-size: 17px; line-height: 30px; margin-top: 45px; \r\n");
      out.write("            width: max-content;\">소속 훈련사가 항시 대기하여, 펫시팅 교육<br>\r\n");
      out.write("            및 위험 상황 발생 시 언제든 상담해드려요.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"width: 273px; align-items: center;\">\r\n");
      out.write("            <img alt=\"\" src=\"/resources/img/member/가입비월회비무료.png\" style=\"height: 120px; \r\n");
      out.write("            display: block; margin-left: -15px;\">\r\n");
      out.write("            <p style=\"margin-top: 21px; color: rgb(77, 80, 85); font-size: 25px; line-height: 30px; \r\n");
      out.write("            letter-spacing: -0.3px; font-weight: 500;\">가입비, 월회비 무료</p>\r\n");
      out.write("            <p style=\"color: rgb(77, 80, 85); font-size: 17px; line-height: 30px; margin-top: 45px; \r\n");
      out.write("            width: max-content;\">펫시스터즈는 별도의 활동 비용을 받지 않습니다.<br>\r\n");
      out.write("            금액 부담 없이 펫시스터즈에서 활동해 보세요.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"width: 273px; align-items: center;\">\r\n");
      out.write("            <img alt=\"\" src=\"/resources/img/member/국내유일펫시터보험.png\" style=\"height: 120px; \r\n");
      out.write("            display: block; margin-left: -15px;\">\r\n");
      out.write("            <p style=\"margin-top: 21px; color: rgb(77, 80, 85); font-size: 25px; line-height: 30px; \r\n");
      out.write("            letter-spacing: -0.3px; font-weight: 500;\">국내 유일 펫시터 보험</p>\r\n");
      out.write("            <p style=\"color: rgb(77, 80, 85); font-size: 17px; line-height: 30px; margin-top: 45px; \r\n");
      out.write("            width: max-content;\">펫시터님 상해에 병원 진료비 최대 1회 10만원,<br>\r\n");
      out.write("            반려동물 상해에 최대 100만원을 지원합니다.</p>\r\n");
      out.write("            <p style=\"margin-top: 27px; font-size: 15px; color: rgb(153, 157, 167);\">\r\n");
      out.write("              펫시터님 귀책 사유일 경우 보험 지원 불가</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 로그인 검사 후 지원폼 포워딩 (인터셉터 등록 후 주석처리 예정) -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    	<script>\r\n");
      out.write("    	  var isLoggedIn = ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(";\r\n");
      out.write("    	  \r\n");
      out.write("    	  function checkLogin() {\r\n");
      out.write("    	    if (!isLoggedIn) {\r\n");
      out.write("    	      // 만약 로그인되지 않은 상태라면 경고 알림창을 띄우고 접근을 차단합니다.\r\n");
      out.write("    	      alert(\"로그인이 필요합니다.\");\r\n");
      out.write("    	      window.location.href = \"loginForm.me\";\r\n");
      out.write("    	      return false;\r\n");
      out.write("    	    }\r\n");
      out.write("\r\n");
      out.write("    	    // 로그인된 상태라면 정상적으로 페이지로 이동합니다.\r\n");
      out.write("    	    return true;\r\n");
      out.write("    	  }\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 본문 끝 -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/supportInfo.jsp(147,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("isLoggedIn");
      // /WEB-INF/views/member/supportInfo.jsp(147,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/supportInfo.jsp(147,4) '${not empty loginUser}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${not empty loginUser}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/member/supportInfo.jsp(147,4) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("request");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/member/supportInfo.jsp(149,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLoggedIn}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
